apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: exam-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exam-app
  template:
    metadata:
      labels:
        app: exam-app
    spec:
      containers:
        - name: exam-container
          # Replace this image with your built/pushed image if different
          image: atulkamble/exam:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
